### ISSUE TITLE
Remove fancontrol installation / startup

### ISSUE THREAD

**Issue by jleveque** [Ingrasys-sonic/sonic-platform-modules-ingrasys#1]
I have created a PR @ https://github.com/Azure/sonic-buildimage/pull/735 which installs fancontrol in the platform-monitor docker and checks for a fancontrol config file in your platform directory.

Therefore, you should be able to remove all code pertaining to the installation and startup of the fancontrol service from this repo. As long as your configuration file is in the right location for each platform in sonic-buildimage (which it appears is true for the three supported Ingrasys platforms), fancontrol will start at boot and use that configuration file.

Please also test that everything works as expected on your platforms. Thanks.

**Comment by wadelnn** [comment]
We already remove all fancontrol service from this repo on [50471fd](https://github.com/Ingrasys-sonic/sonic-platform-modules-ingrasys/commit/50471fdaaa4849c19a97d8623971450f09903d5d). 
We verified that on all platforms and worked good. Thanks for remind this issue.
